dist: trusty
sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_f1dd292de8da_key -iv $encrypted_f1dd292de8da_iv
  -in gae-client-secret.json.enc -out gae-client-secret.json -d
- npm install yarn -g
- yarn install
install:
- yarn run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: gae-client-secret.json
  project: awesome-highway-716
