runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

skip_files:
- ^node_modules(.*/)?$
- ^assets(.*/)?$
- ^content(.*/)?$
- ^templates(.*/)?$

handlers:
- url: /files
  static_dir: built/files

#static site server modified from: https://gist.github.com/darktable/873098
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: built/\1
  upload: built/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: built/\1
  upload: built/(.*\.atom)
  expiration: "1h"

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: built/\1
  upload: built/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  static_files: built/\1
  upload: built/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: built/\1
  upload: built/(.*\.eot)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: built/\1
  upload: built/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: built/\1
  upload: built/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: built/\1
  upload: built/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: built/\1
  upload: built/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: built/\1
  upload: built/(.*\.json)
  expiration: "1h"

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: built/\1
  upload: built/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: built/\1
  upload: built/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: built/\1
  upload: built/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: built/\1
  upload: built/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: built/\1
  upload: built/(.*\.otf)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: built/\1
  upload: built/(.*\.rss)
  expiration: "1h"

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: built/\1
  upload: built/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: built/\1
  upload: built/(.*\.(svg|svgz))

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: built/\1
  upload: built/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: built/\1
  upload: built/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: built/\1
  upload: built/(.*\.txt)

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: built/\1
  upload: built/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: built/\1
  upload: built/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: built/\1
  upload: built/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: built/\1
  upload: built/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: built/\1
  upload: built/(.*\.xml)
  expiration: "1h"

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: built/\1
  upload: built/(.*\.xpi)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|JPG|png))
  static_files: built/\1
  upload: built/(.*\.(bmp|gif|ico|jpeg|jpg|JPG|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: built/\1
  upload: built/(.*\.(mid|midi|mp3|wav))

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: built/\1
  upload: built/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: built/\1
  upload: built/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /(.+)/
  static_files: built/\1/index.html
  upload: built/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: built/\1/index.html
  upload: built/(.+)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: built/index.html
  upload: built/index.html
  expiration: "15m"
