application: sallyandjames
version: 2
runtime: php
api_version: 1
threadsafe: true


handlers:
- url: /assets
  static_dir: assets
  application_readable: true

- url: /
  script: /index.php

- url: /rsvp
  script: /rsvp/index.php


#- url: /admin
#  script: /admin/index.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
