application: sallyandjames
version: 1
runtime: php
api_version: 1
threadsafe: true


handlers:
- url: /assets
  static_dir: assets
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /.*
  script: index.php
